spring:
  application:
    name: "payment-delivery-service"


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        orderEvents-in-0:
          destination: order.event
          content-type: application/json
          group: ${spring.application.name}


