spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      #      routes:
      #        - id: food-service
      #          uri: lb://FOOD-SERVICE
      #          predicates:
      #            - Path=/foods/**
      #          filters:
      #            - RewritePath=/foods/?(?<remaining>.*) , /$\{remaining}
      #            -CircuitBreaker=myCircuitBreaker
      #
      #        - id: restaurant-service
      #          uri: lb://restaurant-service
      #          predicates:
      #            - Path=/restaurants/**
      #          filters:
      #            - RewritePath=/restaurants/?(?<remaining>.*) , /$\{remaining}

      discovery:
        locator:
          enabled: false
      httpclient:
        response-timeout: 5s
        connect-timeout: 1000
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8088/realms/substring/protocol/openid-connect/certs"






eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9095

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Api Gateway"
    description: "This is api gateway for common entry point"
    version: "1.0V"

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000

