spring:
  application:
    name: "food-service"
  config:
    import: "configserver:http://localhost:9096/"
  profiles:
    active: prod

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    eureka configurations
#database in important