spring:
  application:
    name: "order-service"
  cloud:
    function:
      web:
        path: "/api"
      definition: test|test2
    stream:
      bindings:
        orderCreated-out-0:
          destination: order.event
          content-type: application/json
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092


#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9097

